# Generated by Django 6.0.5 on 2026-05-28 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_customers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_customers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('returning_customers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cart_abandonment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_orders', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_items_sold', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('current_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('units_sold', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('views_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-revenue'],
                'unique_together': {('date', 'product_id')},
            },
        ),
    ]
